(() => {
  "use strict";

  const S = globalThis.MreoService;
  const C = globalThis.MreoCore;
  const $ = (id) => document.getElementById(id);
  if (!S || !C || !$("auction-handoff")) return;

  let refreshToken = 0;

  const cashNumber = (value) => {
    const n = Number(value || 0);
    return Number.isFinite(n) && n > 0 ? Math.round(n) : 0;
  };

  const cash = (value) => new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
    maximumFractionDigits: 0
  }).format(cashNumber(value));

  function currentView() {
    return $("view-seller")?.getAttribute("aria-pressed") === "true" ? "seller" : "buyer";
  }

  function buildWorkspaceUrl(auction, view, amount) {
    const query = new URLSearchParams();
    query.set("type", auction.kind === "portfolio" ? "portfolio" : "property");
    query.set("auction", auction.id);
    query.set(auction.kind === "portfolio" ? "title" : "address", auction.title);
    if (amount) query.set("price", String(amount));
    if (auction.kind === "portfolio") query.set("count", String(auction.portfolioCount || auction.portfolio?.length || 0));
    query.set("role", view);
    return `coordination.html?${query.toString()}`;
  }

  function downloadPackage(auction, view, amount) {
    const seller = view === "seller";
    const heading = seller ? "MREO DEMONSTRATION — SELLER CLOSING HANDOFF PACKAGE" : "MREO DEMONSTRATION — ACQUISITION PACKAGE";
    const lines = [
      heading,
      "",
      `Property: ${auction.title}`,
      `Auction: ${auction.id}`,
      `Completed sale amount: ${cash(amount)}`,
      `Listing type: ${auction.kind === "portfolio" ? "Portfolio" : "Property"}`,
      "",
      seller ? "Seller handoff materials:" : "Buyer acquisition materials:",
      seller ? "• Sale and auction result summary" : "• Acquisition confirmation",
      "• Shared property information packet",
      "• Auction result summary",
      "• Closing readiness checklist",
      "• Coordination handoff sheet",
      "",
      seller
        ? "Open the MREO property workspace to follow title / settlement requirements and the same service-provider activity visible to the buyer and participating companies."
        : "Open the MREO property workspace to continue through Transfer, Improve, Represent, and Rent / Manage while all resulting documents remain attached to this property record.",
      "",
      "This file is fictional demonstration material generated by the MREO prototype."
    ];
    const blob = new Blob([lines.join("\n")], {type:"text/plain;charset=utf-8"});
    const url = URL.createObjectURL(blob);
    const anchor = document.createElement("a");
    const slug = String(auction.title || "property").toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "").slice(0, 60) || "property";
    anchor.href = url;
    anchor.download = seller ? `mreo-${slug}-seller-closing-handoff.txt` : `mreo-${slug}-acquisition-package.txt`;
    document.body.appendChild(anchor);
    anchor.click();
    anchor.remove();
    setTimeout(() => URL.revokeObjectURL(url), 1000);
  }

  function hideHandoff(container) {
    if (!container.hidden) container.hidden = true;
    if (container.childNodes.length) container.replaceChildren();
  }

  async function refreshHandoff() {
    const token = ++refreshToken;
    const container = $("auction-handoff");
    const select = $("auction-select");
    if (!container || !select?.value || $("auction-content")?.hidden) {
      if (container) hideHandoff(container);
      return;
    }

    const view = currentView();
    const actor = $("test-actor")?.value || undefined;
    try {
      const result = await S.auction(select.value, view, actor);
      if (token !== refreshToken) return;
      const auction = result.auction;
      const eligible = auction.status === "closed" && auction.saleCompleted && (
        view === "seller" ? result.isSeller : auction.viewerOutcome === "won"
      );
      if (!eligible) {
        hideHandoff(container);
        return;
      }

      const top = C.highest(auction);
      const amount = cashNumber(top?.amount);
      const link = buildWorkspaceUrl(auction, view, amount);
      const seller = view === "seller";
      const heading = seller ? "Sale complete. Continue to closing and handoff." : "Purchase complete. Your property workspace is ready.";
      const copy = seller
        ? "Download the seller closing handoff now, then open the shared workspace to follow title and transfer activity and see the same provider requests from the seller side."
        : "Download the acquisition package now, then open the shared property workspace to continue through Transfer, Improve, Represent, and Rent / Manage.";
      const label = seller ? "Open seller closing workspace →" : "Open acquired-property workspace →";
      const downloadLabel = seller ? "Download seller closing package" : "Download acquisition package";
      const html = `<section class="form-panel" aria-label="Continue to property workspace"><p class="section-label">Next stage · MREO property workspace</p><h2>${heading}</h2><p>${copy}</p><div class="form-actions"><button type="button" class="secondary-button" data-auction-package>${downloadLabel}</button><a class="primary-button button-blue" href="${link}">${label}</a></div></section>`;

      if (container.innerHTML !== html) container.innerHTML = html;
      if (container.hidden) container.hidden = false;
      const packageButton = container.querySelector("[data-auction-package]");
      if (packageButton && packageButton.dataset.bound !== "true") {
        packageButton.dataset.bound = "true";
        packageButton.addEventListener("click", () => downloadPackage(auction, view, amount));
      }
    } catch {
      if (token === refreshToken) hideHandoff(container);
    }
  }

  const observer = new MutationObserver(() => refreshHandoff());
  [$("auction-result"), $("seller-private")].filter(Boolean).forEach((element) => observer.observe(element, {subtree:true, childList:true, attributes:true, characterData:true}));
  [$("auction-select"), $("test-actor")].filter(Boolean).forEach((element) => element.addEventListener("change", refreshHandoff));
  [$("view-buyer"), $("view-seller"), $("finish-auction"), $("complete-sale")].filter(Boolean).forEach((element) => element.addEventListener("click", () => setTimeout(refreshHandoff, 80)));
  setInterval(refreshHandoff, 2000);
  refreshHandoff();
})();
